#!/usr/bin/env ruby
# frozen_string_literal: true

require 'apple_peeler/cli'
require 'vcr'
require 'net/http'

VCR.configure do |config|
  config.hook_into :webmock
  config.cassette_library_dir = 'fixtures/vcr_cassettes'
end

ApplePeeler::CLI.run(ARGV)
