name: App Store Connect API

on:
  push:

jobs:
  build:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: "Generate"
        runs:
          using: 'docker'
          image: 'Dockerfile'
