name: App Store Connect API

on:
  push:

jobs:
  appstoreconnectapi:
    name: App Store Connect API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t apple_peeler:latest
      - name: Peel
        run: docker run apple_peeler bundle exec ./exe/apple_peeler
