---
name: App Store Connect API
on:
  push:
jobs:
  appstoreconnectapi:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t apple_peeler:latest
      - name: RSpec
        run: docker run apple_peeler bundle exec rspec
      - name: Rubocop
        run: docker run apple_peeler bundle exec rubocop
